version: 2
# TODO add goreleaser cross
builds:
  - main: ./cmd/crie
    env:
      - CGO_ENABLED=1
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
    goos:
      - linux
    goarch:
      - amd64

homebrew_casks:
  - repository:
      owner: tyhal
      name: homebrew-crie
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    completions:
      bash: res/completion/crie.bash
      zsh: res/completion/crie.zsh
      fish: res/completion/crie.fish
    homepage: "https://github.com/tyhal/crie"
    description: "Universal meta-linter using containerized execution "
    license: "MIT"

archives:
  - formats: ['tar.gz']
release:
  github:
    owner: tyhal
    name: crie
