queue_rules:
  - name: default
    queue_conditions:
      - status-success=crie-test
      - status-success=SonarCloud Code Analysis
      - status-success=GitGuardian Security Checks
      - or:
          - check-success=img-apk-test / docker-build
          - check-skipped=img-apk-test / docker-build
      - or:
          - check-success=img-go-test / docker-build
          - check-skipped=img-go-test / docker-build
      - or:
          - check-success=img-npm-test / docker-build
          - check-skipped=img-npm-test / docker-build
      - or:
          - check-success=img-pip-test / docker-build
          - check-skipped=img-pip-test / docker-build

pull_request_rules:
  - name: automatic merge for Dependabot pull requests
    conditions:
      - base=main
      - author~=^dependabot(|-preview)\[bot\]$
    actions:
      queue:
        name: default
  - name: automatic merge for Renovate pull requests
    conditions:
      - base=main
      - author=renovate[bot]
    actions:
      queue:
        name: default
  - name: automatic merge for Synk pull requests
    conditions:
      - base=main
      - title~=^\[Snyk\]
      - head~=^snyk-fix
      - check-success~=^security/snyk
    actions:
      queue:
        name: default
  - name: automatic merge for ImgBot pull requests
    conditions:
      - base=main
      - author=imgbot[bot]
    actions:
      queue:
        name: default