queue_rules:
  - name: default
    conditions:
      - check-success=docker-build

pull_request_rules:
  - name: automatic merge for Dependabot pull requests
    conditions:
      - base=main
      - author~=^dependabot(|-preview)\[bot\]$
      - check-success=docker-build
    actions:
      queue:
        name: default
  - name: automatic merge for Renovate pull requests
    conditions:
      - base=main
      - author=renovate[bot]
      - check-success=docker-build
    actions:
      queue:
        name: default
  - name: automatic merge for Synk pull requests
    conditions:
      - base=main
      - title~=^\[Snyk\]
      - head~=^snyk-fix
      - check-success~=^security/snyk
      - check-success=docker-build
    actions:
      queue:
        name: default
  - name: automatic merge for ImgBot pull requests
    conditions:
      - base=main
      - author=imgbot[bot]
      - check-success=docker-build
    actions:
      queue:
        name: default
