version: 2
builds:
  - main: ./cmd/crie
    tool: echo
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: darwin
        goarch: amd64
      - goos: linux
        goarch: arm64
    hooks:
      pre:
        - sh ./script/download {{ .Version }} {{ .Os }} {{ .Arch }} {{ .Target }}
archives:
  - formats: ['tar.gz']
    files:
      - res/completion/*
      - README.md
      - LICENSE
homebrew_casks:
  - repository:
      owner: tyhal
      name: homebrew-crie
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    url:
      template: "https://github.com/tyhal/crie/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
    completions:
      bash: res/completion/crie.bash
      zsh: res/completion/crie.zsh
      fish: res/completion/crie.fish
    homepage: "https://github.com/tyhal/crie"
    description: "Universal meta-linter using containerized execution "
    license: "MIT"
release:
  github:
    owner: tyhal
    name: crie
  replace_existing_artifacts: true