version: 2
builds:
  - main: ./cmd/crie
    env:
      - CGO_ENABLED=1
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
    goos:
      - linux
    goarch:
      - amd64
    hooks:
      pre:
        - sh ./script/bootstrap
checksum:
  disable: true
archives:
  - formats: ['tar.gz']
release:
  github:
    owner: tyhal
    name: crie
  replace_existing_artifacts: true