queue_rules:
  - name: default
    conditions:
      - status-success=Docker / test (pull_request)

pull_request_rules:
  - name: automatic merge for Dependabot pull requests
    conditions:
      - base=master
      - author~=^dependabot(|-preview)\[bot\]$
      - status-success=Docker / test (pull_request)
    actions:
      queue:
        name: default
  - name: automatic merge for Renovate pull requests
    conditions:
      - base=master
      - author=renovate[bot]
      - status-success=Docker / test (pull_request)
    actions:
      queue:
        name: default
  - name: automatic merge for Synk pull requests
    conditions:
      - base=master
      - title~=^\[Snyk\]
      - head~=^snyk-fix
      - check-success~=^security/snyk
      - status-success=Docker / test (pull_request)
    actions:
      queue:
        name: default
  - name: automatic merge for ImgBot pull requests
    conditions:
      - base=master
      - author=imgbot[bot]
      - status-success=Docker / test (pull_request)
    actions:
      queue:
        name: default
