pull_request_rules:
  - name: automatic merge for Dependabot pull requests
    conditions:
      - author=dependabot-preview[bot]
      - status-success=ci/dockercloud
      - status-success=License Compliance
    actions:
      merge:
        method: merge
  - name: automatic merge for Renovate pull requests
    conditions:
      - author=renovate[bot]
      - status-success=ci/dockercloud
      - status-success=License Compliance
    actions:
      merge:
        method: merge
  - name: automatic merge for Synk pull requests
    conditions:
      - author=snyk-bot[bot]
      - status-success=ci/dockercloud
      - status-success=License Compliance
    actions:
      merge:
        method: merge
  - name: automatic merge for Tyhal pull requests
    conditions:
      - author=tyhal
      - status-success=ci/dockercloud
      - status-success=License Compliance
    actions:
      merge:
        method: merge
