coverage:
  status:
    patch:
      default:
        target: 50%
  ignore:
    - cmd/crie/main.go # until cli testing is decided to be unit tests or some other solution
    - cmd/crie/cmd/commands.go
