coverage:
  status:
    patch:
      default:
        target: 50%
  ignore:
    - internal/cli/root.go # until cli testing is decided to be unit tests or some other solution
    - internal/cli/commands.go
    - cmd/crie/main.go
    - cmd/docgen/main.go
