#!/bin/sh
set -xe

has_command() {
	command -v "$1" >/dev/null 2>&1
}

install_brew() {
  brew install \
    pkg-config \
    gpgme \
    gnupg
}

install_apt() {
  sudo apt-get update
  sudo apt-get install -y \
          libgpgme-dev \
          libbtrfs-dev \
          libdevmapper-dev \
          pkg-config
}

if has_command brew; then install_brew
elif has_command apt; then install_apt
else echo "unknown package manager"
fi