#!/bin/sh
set -xe

has_command() {
	command -v "$1" >/dev/null 2>&1
}

install_brew() {
	xargs brew install <"$(dirname "$0")/pkgs/brew.txt"
}

install_apt() {
	sudo apt-get update -qq
	xargs sudo apt-get install -y --no-install-recommends <"$(dirname "$0")/pkgs/apt.txt"
}

if has_command brew; then
	install_brew
elif has_command apt; then
	install_apt
else
	echo "unknown package manager"
fi
