#!/bin/sh
set -e

# Simple script to run the crie container

CRIE_VERSION=${CRIE_VERSION:-latest}

if [ -n "$HOST_ARCH" ]; then
	HOST_ARCH="-$HOST_ARCH"
fi

IMAGE="tyhal/crie$HOST_ARCH:$CRIE_VERSION"
D_RUN="run --user $(id -u):$(id -g) --rm -t"

if [ "$1" = "update" ]; then
	docker pull "$IMAGE"
	exit 0
fi
if [ "$1" = "install" ]; then
	cp "$0" /usr/local/bin
	cp -r "$(dirname "$0")/../conf" /etc/crie/
	echo " ✔️   Installed"
	exit 0
fi

bash -c "docker $D_RUN -v $PWD:$PWD -w $PWD $IMAGE $*"
