#!/bin/sh
set -e

cd "$(dirname "$0")/.."
. script/env

# res

go run ./cmd/crie completion zsh >res/completion/crie.zsh
go run ./cmd/crie completion bash >res/completion/crie.bash
go run ./cmd/crie completion fish >res/completion/crie.fish

go run ./cmd/crie schema lang >./res/schema/lang.json
go run ./cmd/crie schema proj >./res/schema/proj.json

# docs

echo '```' >./doc/supported_languages.md
# point to non-existent lang to skip non-defaults
go run ./cmd/crie ls --lang-conf="not.lang.yml" >>./doc/supported_languages.md
echo '```' >>./doc/supported_languages.md

go run ./cmd/docgen -out ./doc/cli -format markdown
