#!/bin/sh
set -e

cd "$(dirname "${0}")/.."

go test -coverprofile=coverage.out ./...

# E2E TESTS ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
set -x
go run ./cmd/crie --help
go run ./cmd/crie chk
go run ./cmd/crie ls
go run ./cmd/crie fmt
go run ./cmd/crie chk --git-diff 9 -j
go run ./cmd/crie chk --only golang
go run ./cmd/crie non
set +x

verify/script/test

echo "! PASS !"
