name: docker-img-apk
on:
  push:
    branches:
      - main
    tags:
      - v*
  pull_request:
    paths: ['img/npm/*','.github/workflows/docker-build-template.yml','.github/workflows/docker-img-npm.yml']

jobs:
  build:
    uses: ./.github/workflows/docker-build-template.yml
    with:
      img: 'npm'

  push:
    uses: ./.github/workflows/docker-push-template.yml
    with:
      img: 'npm'
    secrets:
      DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
      DOCKER_HUB_ACCESS_TOKEN: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}