name: docker-img-apk
on:
  push:
    branches:
      - main
    tags:
      - v*
  pull_request:
    paths: ['img/apk/*']

jobs:
  build:
    uses: ./.github/workflows/docker-build-template.yml
    with:
      img: 'apk'

  push:
    uses: ./.github/workflows/docker-push-template.yml
    with:
      img: 'apk'