name: docker-img-npm
on:
  push:
    branches:
      - main
    tags:
      - v*
  pull_request:
    paths: ['img/pip/*','.github/workflows/docker-build-template.yml','.github/workflows/docker-img-pip.yml']

jobs:
  build:
    uses: ./.github/workflows/docker-build-template.yml
    with:
      img: 'pip'

  push:
    uses: ./.github/workflows/docker-push-template.yml
    with:
      img: 'pip'
    secrets:
      DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
      DOCKER_HUB_ACCESS_TOKEN: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}