name: img-apk
permissions:
  contents: read
  packages: read
on:
  push:
    branches:
      - main
    tags:
      - v*
  pull_request:
    paths: ['img/apk/*', '.github/workflows/docker-build-template.yml', 'img-apk.yml']
jobs:
  img-apk-test:
    uses: ./.github/workflows/docker-build-template.yml
    with:
      img: 'apk'
  img-apk-push:
    permissions:
      contents: read
      packages: write
    uses: ./.github/workflows/docker-push-template.yml
    with:
      img: 'apk'
