name: img-pip
permissions:
  contents: read
on:
  push:
    branches:
      - main
    tags:
      - v*
  pull_request:
    paths: ['img/pip/*', '.github/workflows/docker-build-template.yml', 'img-pip.yml']
jobs:
  img-pip-test:
    uses: ./.github/workflows/docker-build-template.yml
    with:
      img: 'pip'
  img-pip-push:
    uses: ./.github/workflows/docker-push-template.yml
    with:
      img: 'pip'
    secrets:
      DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
      DOCKER_HUB_ACCESS_TOKEN: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
