name: img-go
permissions:
  contents: read
  packages: read
on:
  push:
    branches:
      - main
    tags:
      - v*
  pull_request:
    paths: ['img/go/*', '.github/workflows/docker-build-template.yml', 'img-go.yml']
jobs:
  img-go-test:
    uses: ./.github/workflows/docker-build-template.yml
    with:
      img: 'go'
  img-go-push:
    permissions:
      contents: read
      packages: write
    uses: ./.github/workflows/docker-push-template.yml
    with:
      img: 'go'
