name: img-apk
on:
  push:
    branches:
      - main
    tags:
      - v*
  pull_request:
    paths: [ 'img/apk/*','.github/workflows/docker-build-template.yml','img-apk.yml' ]

jobs:
  img-apk-test:
    uses: ./.github/workflows/docker-build-template.yml
    with:
      img: 'apk'

  img-apk-push:
    uses: ./.github/workflows/docker-push-template.yml
    with:
      img: 'apk'
    secrets:
      DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
      DOCKER_HUB_ACCESS_TOKEN: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
