name: img-npm
permissions:
  contents: read
  packages: read
on:
  push:
    branches:
      - main
    tags:
      - v*
  pull_request:
    paths: ['img/npm/*', '.github/workflows/docker-build-template.yml', 'img-npm.yml']
jobs:
  img-npm-test:
    uses: ./.github/workflows/docker-build-template.yml
    with:
      img: 'npm'
  img-npm-push:
    permissions:
      contents: read
      packages: write
    uses: ./.github/workflows/docker-push-template.yml
    with:
      img: 'npm'