name: img-npm
on:
  push:
    branches:
      - main
    tags:
      - v*
  pull_request:
    paths: [ 'img/npm/*','.github/workflows/docker-build-template.yml','img-npm.yml' ]

jobs:
  img-npm-test:
    uses: ./.github/workflows/docker-build-template.yml
    with:
      img: 'npm'

  img-npm-push:
    uses: ./.github/workflows/docker-push-template.yml
    with:
      img: 'npm'
    secrets:
      DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
      DOCKER_HUB_ACCESS_TOKEN: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
