name: img-pip
permissions:
  contents: read
  packages: read
on:
  push:
    branches:
      - main
    tags:
      - v*
  pull_request:
    paths: ['img/pip/*', '.github/workflows/docker-build-template.yml', 'img-pip.yml']
jobs:
  img-pip-test:
    uses: ./.github/workflows/docker-build-template.yml
    with:
      img: 'pip'
  img-pip-push:
    permissions:
      contents: read
      packages: write
    uses: ./.github/workflows/docker-push-template.yml
    with:
      img: 'pip'
