name: img-go
on:
  push:
    branches:
      - main
    tags:
      - v*
  pull_request:
    paths: [ 'img/go/*','.github/workflows/docker-build-template.yml','img-go.yml' ]

jobs:
  img-go-test:
    uses: ./.github/workflows/docker-build-template.yml
    with:
      img: 'go'

  img-go-push:
    uses: ./.github/workflows/docker-push-template.yml
    with:
      img: 'go'
    secrets:
      DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
      DOCKER_HUB_ACCESS_TOKEN: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}